#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize real_robot_plan.npz pose trajectories.")
    parser.add_argument("--plan-npz", required=True, help="real_robot_plan.npz generated by prepare_real_robot_plan.py.")
    parser.add_argument("--output", help="Optional output image path. If omitted, show an interactive window.")
    parser.add_argument("--axis-scale", type=float, default=0.02, help="Length of pose coordinate axes in plot units.")
    parser.add_argument("--stride", type=int, default=20, help="Draw one pose frame every N frames when --show-axes is enabled.")
    parser.add_argument("--show-invalid", action="store_true", help="Draw object/EE positions for invalid Kabsch frames.")
    parser.add_argument("--show-axes", action="store_true", help="Draw coordinate axes along the object and EE trajectories.")
    parser.add_argument("--hide-ee", action="store_true", help="Hide dense EE trajectory and show only waypoints.")
    return parser.parse_args()


def require_array(data: np.lib.npyio.NpzFile, key: str) -> np.ndarray:
    if key not in data:
        raise KeyError(f"{key} is missing from {data.files}")
    return np.asarray(data[key])


def set_equal_axes(ax, points: np.ndarray) -> None:
    finite_points = points[np.all(np.isfinite(points), axis=1)]
    if len(finite_points) == 0:
        return
    mins = finite_points.min(axis=0)
    maxs = finite_points.max(axis=0)
    center = (mins + maxs) * 0.5
    radius = float(np.max(maxs - mins) * 0.5)
    radius = max(radius, 0.05)
    ax.set_xlim(center[0] - radius, center[0] + radius)
    ax.set_ylim(center[1] - radius, center[1] + radius)
    ax.set_zlim(center[2] - radius, center[2] + radius)


def draw_pose_axes(ax, pose: np.ndarray, scale: float, label: str | None = None) -> None:
    origin = pose[:3, 3]
    axes = pose[:3, :3]
    colors = ("r", "g", "b")
    for axis_idx, color in enumerate(colors):
        vector = axes[:, axis_idx] * scale
        ax.quiver(
            origin[0],
            origin[1],
            origin[2],
            vector[0],
            vector[1],
            vector[2],
            color=color,
            linewidth=1.2,
            arrow_length_ratio=0.25,
        )
    if label:
        ax.text(origin[0], origin[1], origin[2], label, fontsize=8)


def plot_masked_segments(ax, positions: np.ndarray, mask: np.ndarray, *args, **kwargs) -> None:
    first_label = kwargs.pop("label", None)
    start = None
    label = first_label
    for idx, is_valid in enumerate(mask):
        if is_valid and start is None:
            start = idx
        if start is not None and (not is_valid or idx == len(mask) - 1):
            end = idx if not is_valid else idx + 1
            if end - start >= 2:
                ax.plot(
                    positions[start:end, 0],
                    positions[start:end, 1],
                    positions[start:end, 2],
                    *args,
                    label=label,
                    **kwargs,
                )
                label = None
            elif end - start == 1:
                ax.scatter(
                    positions[start, 0],
                    positions[start, 1],
                    positions[start, 2],
                    s=20,
                    label=label,
                )
                label = None
            start = None


def plot_plan(
    plan_npz: Path,
    output_path: Path | None,
    *,
    axis_scale: float,
    stride: int,
    show_invalid: bool,
    show_axes: bool,
    hide_ee: bool,
) -> None:
    data = np.load(plan_npz)
    object_poses = require_array(data, "object_poses_base")
    ee_poses = require_array(data, "ee_poses_base")
    waypoint_names = require_array(data, "waypoint_names").astype(str)
    waypoint_poses = require_array(data, "waypoint_poses")
    valid = require_array(data, "object_pose_valid").astype(bool)
    kabsch_rms = require_array(data, "kabsch_rms")

    if object_poses.shape != ee_poses.shape or object_poses.ndim != 3 or object_poses.shape[1:] != (4, 4):
        raise ValueError(
            "object_poses_base and ee_poses_base must both have shape (T, 4, 4); "
            f"got {object_poses.shape} and {ee_poses.shape}"
        )

    object_positions = object_poses[:, :3, 3]
    ee_positions = ee_poses[:, :3, 3]
    waypoint_positions = waypoint_poses[:, :3, 3]
    frame_mask = np.ones(len(valid), dtype=bool) if show_invalid else valid

    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection="3d")
    ax.set_title(f"Real Robot Plan: {plan_npz.name}\nvalid Kabsch frames: {int(valid.sum())}/{len(valid)}")
    ax.set_xlabel("X (base/world)")
    ax.set_ylabel("Y (base/world)")
    ax.set_zlabel("Z (base/world)")

    invalid_positions = object_positions[~valid]
    if show_invalid and len(invalid_positions):
        ax.scatter(
            invalid_positions[:, 0],
            invalid_positions[:, 1],
            invalid_positions[:, 2],
            s=8,
            c="lightgray",
            label="object invalid frames",
        )

    if np.any(frame_mask):
        if show_invalid:
            ax.plot(
                object_positions[frame_mask, 0],
                object_positions[frame_mask, 1],
                object_positions[frame_mask, 2],
                "-o",
                markersize=3,
                linewidth=1.5,
                label="object poses",
            )
        else:
            plot_masked_segments(
                ax,
                object_positions,
                valid,
                "-o",
                markersize=3,
                linewidth=1.5,
                label="object poses",
            )
        if not hide_ee:
            if show_invalid:
                ax.plot(
                    ee_positions[frame_mask, 0],
                    ee_positions[frame_mask, 1],
                    ee_positions[frame_mask, 2],
                    "-",
                    linewidth=1.2,
                    alpha=0.7,
                    label="EE poses",
                )
            else:
                plot_masked_segments(
                    ax,
                    ee_positions,
                    valid,
                    "-",
                    linewidth=1.2,
                    alpha=0.7,
                    label="EE poses",
                )

    if show_axes:
        for frame_idx in range(0, len(object_poses), max(stride, 1)):
            if not show_invalid and not valid[frame_idx]:
                continue
            draw_pose_axes(ax, object_poses[frame_idx], axis_scale, label=f"obj{frame_idx}" if frame_idx == 0 else None)
            if not hide_ee:
                draw_pose_axes(ax, ee_poses[frame_idx], axis_scale, label=f"ee{frame_idx}" if frame_idx == 0 else None)

    for name, pose in zip(waypoint_names, waypoint_poses):
        position = pose[:3, 3]
        ax.scatter(position[0], position[1], position[2], s=80, marker="*", label=f"waypoint {name}")
        draw_pose_axes(ax, pose, axis_scale * 1.5, label=name)

    all_points = np.concatenate([object_positions, ee_positions, waypoint_positions], axis=0)
    set_equal_axes(ax, all_points)
    ax.legend(loc="best")
    ax.grid(True)

    finite_rms = kabsch_rms[np.isfinite(kabsch_rms)]
    rms_text = "n/a" if len(finite_rms) == 0 else f"max finite Kabsch RMS: {float(finite_rms.max()):.4f} m"
    fig.text(0.02, 0.02, rms_text, fontsize=10)
    fig.tight_layout()

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(output_path, dpi=180)
        print(f"Saved real robot plan visualization to: {output_path}")
    else:
        plt.show()


def main() -> None:
    args = parse_args()
    plot_plan(
        Path(args.plan_npz).expanduser().resolve(),
        Path(args.output).expanduser().resolve() if args.output else None,
        axis_scale=args.axis_scale,
        stride=args.stride,
        show_invalid=args.show_invalid,
        show_axes=args.show_axes,
        hide_ee=args.hide_ee,
    )


if __name__ == "__main__":
    main()
